stages:
  - build
  - notify

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.9.0-debug
    entrypoint: [""]
  script:
    - if [ "$AUTH" == "" ]; then exit 1 ;fi;
    - if [ "$PUSH_IMAGE" == "" ]; then exit 1 ;fi;
    - |
      cat > /kaniko/.docker/config.json << EOF
      {
        "auths": {
          "https://index.docker.io/v1/": {
            "auth": "${AUTH}"
          }
        }
      }
      EOF
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination ${PUSH_IMAGE}
  tags:
    - zimaboard
  only:
    - main

notify:
  stage: notify
  image:
    name: alpine/curl
  script:
    - echo "nameserver 8.8.8.8" >> /etc/resolv.conf
    - if [ -n ${BARK_TOKEN} ]; then curl https://api.day.app/${BARK_TOKEN}/docs%20ci%20build%20success; fi;
  tags:
    - zimaboard
  only:
    - main
