services:

    docs:
        platform: linux/amd64
        image: squidfunk/mkdocs-material
        restart: unless-stopped
        mem_limit: 128m
        volumes:
          - ./docs:/docs/docs
          - ./mkdocs.yml:/docs/mkdocs.yml


        labels:
            - traefik.enable=true
            - traefik.http.routers.docs.rule=Host(`docs.docker.localhost`)
            - traefik.http.routers.docs.entrypoints=web
